services:
    db:
        image: mysql:8.0
        container_name: db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: rails-app
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql

    app:
        container_name: web
        build: .
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        volumes:
            - ".:/app"
        ports:
            - "3001:3000"
        depends_on:
            - db
        environment:
            DB_USER: root
            DB_NAME: rails-app
            DB_PASSWORD: password
            DB_HOST: db
        stdin_open: true
        tty: true

volumes:
    db_data: